# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: docker://conanio/gcc9
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Set up build environment
        run: |
          sudo apt-get install -y --force-yes --no-install-recommends python3-pip python3-setuptools doxygen
          sudo python3 -m pip install --upgrade conan
          sudo python3 -m pip install sphinx
          sudo python3 -m pip install gcovr
          python3 -m pip install breathe

      - name: Configure build environment
        run: |
          conan user

      - name: Build package
        run: |
          conan install . -if build -b missing
          conan build . -bf build
      
      - name: Run tests
        run: |
          ./build/fibonacci/bin/fibonacci_test --gtest_output="xml:testing-report.xml"
          gcovr . build/ --xml-pretty -o coverage-report.xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-report.xml
          directory: ./
          fail_ci_if_error: true
          verbose: true

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build
